### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by liampower** [AustP/git-go#4]
Reproduction:
1. `git push origin master`
2. ^C interrupt
3. `clear`

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1
**Thrown From**: [git-go](https://github.com/austp/git-go) package, v1.0.1
### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at Object.module.exports.enterHandler (C:\Users\\.atom\packages\git-go\lib\console.coffee:279:20)
  at Object.module.exports.inputKeyupHandler (C:\Users\\.atom\packages\git-go\lib\console.coffee:178:32)
  at atom-text-editor.<anonymous> (C:\Users\\.atom\packages\git-go\lib\console.coffee:156:32)
  at atom-text-editor.jQuery.event.dispatch (C:\Users\\.atom\packages\git-go\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
  at atom-text-editor.elemData.handle (C:\Users\\.atom\packages\git-go\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -2:37.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:35.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:39.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:38.3.0 git-go:show (atom-text-editor.editor)
     -1:38 git-go:focus (ol.tabs)
 10x -1:34 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 38x -1:23.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:40.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.1.0 git-go:select-console (atom-text-editor.editor.mini.is-focused)
     -0:34.1.0 git-go:focus (ol.tabs)
  2x -0:16 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "archive-view",
      "spell-check",
      "snippets",
      "open-on-github",
      "metrics",
      "exception-reporting",
      "image-view",
      "styleguide",
      "link",
      "welcome",
      "bookmarks",
      "background-tips",
      "markdown-preview",
      "package-generator",
      "release-notes",
      "autocomplete",
      "git-diff"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
git-go, v1.0.1
language-cmake, v0.1.3
language-glsl, v2.0.0

# Dev
No dev packages
```

**Comment by spaced-out-factory** [comment]
I just got this error too. It a bug.

**Comment by AustP** [comment]
@zachdyer are you on Windows as well?

**Comment by spaced-out-factory** [comment]
Yes.

**Comment by eddowh** [comment]
What a shame, I was digging the console integration. Sad to see this hasn't been resolved yet.

**Comment by AustP** [comment]
I was finally able to reproduce this issue. I believe I have fixed the issue. If you guys continue to have problems let me know.
